/**
 * Central site configuration — update values here without touching page code.
 */
export const siteConfig = {
  name: 'Woven Sage Counseling',
  shortName: 'Woven Sage',
  tagline: 'Clarity through connection',
  url: 'https://wovensage.com',
  contactEmail: 'admin@wovensage.com',
  contactPhone: '561-556-2229',
  contactPhoneHref: 'tel:+15615562229',

  bookingCtaLabel: 'Join our waitlist',
  bookingTrustCopy:
    'We are currently in prelaunch. Share your interest and we will reach out when we open officially.',

  contactFormPrelaunchNote:
    'We are currently in prelaunch and not yet accepting appointments. Submit this form to express your interest — we will contact you when we open officially. Please do not include clinical or health information.',

  contactFormSubmitLabel: 'Join our waitlist',
  contactFormSuccessTitle: 'Thank you — we received your interest.',
  contactFormSuccessMessage:
    'We will contact you at the email you provided when Woven Sage Counseling opens officially.',
  contactFormErrorMessage:
    'Something went wrong sending your message. Please try again or reach us by phone or email.',

  logos: {
    main: '/images/logo-main-transparent.png',
    text: '/images/logo-text.jpg',
    textHeader: '/images/logo-text-header-transparent.png',
    monogram: '/images/logo-ws.jpg',
    monogramFooter: '/images/logo-ws-footer-transparent.png',
    leaf: '/images/logo-leaf.png',
    sageLeaves: '/images/sage-leaves-transparent.png',
    sageBranchHero: '/images/sage-branch-hero-transparent.png',
    sageBranchHeroLeft: '/images/sage-branch-hero-left-transparent.png',
    sageBotanicalHero: '/images/sage-botanical-hero.png',
    chapter2Rest: '/images/chapter-2-rest-cropped.jpg',
    servicesHero: '/images/services-hero-matcha.jpg',
    teamGrowing: '/images/team-growing-bg.jpg',
  },

  /** Formspree form ID — sign up at formspree.io and paste your form ID here */
  formspreeFormId: 'xjgqplvy',

  /** Optional: Cloudflare Web Analytics token from dashboard */
  cloudflareAnalyticsToken: '',

  serviceAreas: [
    'Wellington',
    'Boca Raton',
    'Delray Beach',
    'Lake Worth',
    'Boynton Beach',
  ],

  social: {
    psychologyToday: '',
    linkedin: '',
    instagram: '',
    tiktok: '',
    facebook: '',
  },

  team: {
    founder: {
      name: 'Christian Evans',
      title: 'Founder & Operations Director',
      credentials: 'BS · MMHC',
      pronouns: '',
      bio: 'Christian founded Woven Sage Counseling with a vision to build a thoughtful, connection-centered practice serving clients across South Florida and throughout the state. He leads the practice’s operations, growth, brand, and client experience.',
    },
    clinician: {
      name: 'Michele Evans',
      title: 'Co-Founder & LMHC',
      credentials: 'LMHC · MCAP · EMDR Trained',
      pronouns: 'she/her/hers',
      languages: ['English'],
      license: 'Florida',
      bio: 'Michele provides collaborative, compassionate therapy for adults and young adults navigating anxiety, trauma, depression, relationship challenges, life transitions, and substance use concerns. Her approach combines evidence-based care with warmth, curiosity, and genuine connection.',
      specialties: 'Adults · Young Adults',
    },
  },

  insurance: {
    note: 'We accept many major insurance plans and related networks. Coverage varies by plan, so please confirm your benefits with us before your first session.',
    carriers: [
      {
        id: '90-degree-benefits-caprock',
        name: '90 Degree Benefits - Caprock',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: '90-degree-benefits-houston',
        name: '90 Degree Benefits - Houston',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: '90-degree-benefits-cigna',
        name: '90 Degree Benefits (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: '90-degree-benefits-cigna-north-carolina',
        name: '90 Degree Benefits (Cigna) - North Carolina',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'aci-first-health-network',
        name: 'ACI (First Health Network)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'acs-benefit-services-aetna',
        name: 'ACS Benefit Services (Aetna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'aetna',
        name: 'Aetna',
        aliases: [
          'Aetna Better Health',
        ],
        featured: true,
        status: 'active',
        logo: '/images/carriers/aetna.svg',
      },
      {
        id: 'aetna-medicare-advantage',
        name: 'Aetna Medicare Advantage',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'aither-health-first-health-network',
        name: 'Aither Health (First Health Network)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'all-savers-health-plans',
        name: 'All Savers Health Plans',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'allegiance-by-cigna-healthcare',
        name: 'Allegiance by Cigna Healthcare',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'allegiance-by-cigna-healthcare-claimdoc',
        name: 'Allegiance by Cigna Healthcare (ClaimDOC)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'allied-benefit-systems-aetna',
        name: 'Allied Benefit Systems (Aetna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'allied-benefit-systems-cigna',
        name: 'Allied Benefit Systems (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'allied-health-cigna-indemnity',
        name: 'Allied Health (Cigna) Indemnity',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-from-absolute-total-care',
        name: 'Ambetter from Absolute Total Care',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-from-arizona-complete-health',
        name: 'Ambetter from Arizona Complete Health',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-from-arkansas-health-and-wellness',
        name: 'Ambetter from Arkansas Health and Wellness',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-from-buckeye-health-plan',
        name: 'Ambetter from Buckeye Health Plan',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-from-coordinated-care',
        name: 'Ambetter from Coordinated Care',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-from-home-state-health',
        name: 'Ambetter from Home State Health',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-from-louisiana-healthcare-connections',
        name: 'Ambetter from Louisiana Healthcare Connections',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-from-magnolia-health',
        name: 'Ambetter from Magnolia Health',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-from-meridian',
        name: 'Ambetter from Meridian',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-from-nebraska-total-care',
        name: 'Ambetter from Nebraska Total Care',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-from-new-hampshire-healthy-families',
        name: 'Ambetter from New Hampshire Healthy Families',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-from-pennsylvania-health-and-wellness',
        name: 'Ambetter from Pennsylvania Health & Wellness',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-from-silversummit-healthplan',
        name: 'Ambetter from SilverSummit Healthplan',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-from-superior-healthplan',
        name: 'Ambetter from Superior HealthPlan',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-from-wellcare-of-kentucky',
        name: 'Ambetter from WellCare of Kentucky',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-from-western-sky-community-care',
        name: 'Ambetter from Western Sky Community Care',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-health-florida',
        name: 'Ambetter Health - Florida',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-health-indiana',
        name: 'Ambetter Health - Indiana',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-health-iowa',
        name: 'Ambetter Health - Iowa',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-health-from-peach-state-health-plan',
        name: 'Ambetter Health from Peach State Health Plan',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-health-of-delaware',
        name: 'Ambetter Health of Delaware',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-of-alabama',
        name: 'Ambetter of Alabama',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-of-illinois',
        name: 'Ambetter of Illinois',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-of-north-carolina',
        name: 'Ambetter of North Carolina',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-of-oklahoma',
        name: 'Ambetter of Oklahoma',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ambetter-of-tennessee',
        name: 'Ambetter of Tennessee',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ameriben-solutions-inc-cigna',
        name: 'Ameriben Solutions, Inc. (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ameriben-solutions-inc-partners-direct-health',
        name: 'Ameriben Solutions, Inc. (Partners Direct Health)',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'american-plan-administrators-partners-direct-health',
        name: 'American Plan Administrators (Partners Direct Health)',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'angle-health-aetna-first-health',
        name: 'Angle Health (Aetna/First Health)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'angle-health-cigna',
        name: 'Angle Health (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'anthem-bluecross-blueshield',
        name: 'Anthem BlueCross BlueShield',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'anthem-bluecross-blueshield-of-colorado',
        name: 'Anthem BlueCross BlueShield of Colorado',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'anthem-bluecross-blueshield-of-connecticut',
        name: 'Anthem BlueCross BlueShield of Connecticut',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'anthem-bluecross-blueshield-of-georgia',
        name: 'Anthem BlueCross BlueShield of Georgia',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'anthem-bluecross-blueshield-of-indiana',
        name: 'Anthem BlueCross BlueShield of Indiana',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'anthem-bluecross-blueshield-of-kentucky',
        name: 'Anthem BlueCross BlueShield of Kentucky',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'anthem-bluecross-blueshield-of-maine',
        name: 'Anthem BlueCross BlueShield of Maine',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'anthem-bluecross-blueshield-of-missouri',
        name: 'Anthem BlueCross BlueShield of Missouri',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'anthem-bluecross-blueshield-of-nevada',
        name: 'Anthem BlueCross BlueShield of Nevada',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'anthem-bluecross-blueshield-of-new-hampshire',
        name: 'Anthem BlueCross BlueShield of New Hampshire',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'anthem-bluecross-blueshield-of-new-york',
        name: 'Anthem BlueCross BlueShield of New York',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'anthem-bluecross-blueshield-of-ohio',
        name: 'Anthem BlueCross BlueShield of Ohio',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'anthem-bluecross-blueshield-of-virginia',
        name: 'Anthem BlueCross BlueShield of Virginia',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'anthem-bluecross-blueshield-of-wisconsin',
        name: 'Anthem BlueCross BlueShield of Wisconsin',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'anthem-bluecross-of-california',
        name: 'Anthem BlueCross of California',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'ascension-smarthealth',
        name: 'Ascension (SmartHealth)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'aspirus-health-plan-aetna',
        name: 'Aspirus Health Plan (Aetna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'asr-health-benefits-aetna',
        name: 'ASR Health Benefits (Aetna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'assured-benefit-administrators-cigna',
        name: 'Assured Benefit Administrators (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'auxiant-aetna',
        name: 'Auxiant (Aetna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'auxiant-cigna',
        name: 'Auxiant (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'avmed',
        name: 'AvMed',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'bakers-union-and-felra-health-and-welfare-fund-cigna',
        name: 'Bakers Union and FELRA Health and Welfare Fund (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'banner-health',
        name: 'Banner Health',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'benefit-health-plan-inc-first-health-network',
        name: 'Benefit Health Plan, Inc. (First Health Network)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'blue-cross-blueshield-federal-employee-program-fep',
        name: 'Blue Cross BlueShield Federal Employee Program (FEP)',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'blue-cross-blueshield-of-kansas-city',
        name: 'Blue Cross BlueShield of Kansas City',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'blue-cross-blueshield-of-michigan',
        name: 'Blue Cross BlueShield of Michigan',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'blue-cross-blueshield-of-mississippi',
        name: 'Blue Cross BlueShield of Mississippi',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'blue-cross-blueshield-of-wyoming',
        name: 'Blue Cross BlueShield of Wyoming',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'bluecross-blueshield-of-alabama',
        name: 'BlueCross BlueShield of Alabama',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'bluecross-blueshield-of-arizona',
        name: 'BlueCross BlueShield of Arizona',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'bluecross-blueshield-of-arkansas',
        name: 'BlueCross BlueShield of Arkansas',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'bluecross-blueshield-of-illinois',
        name: 'BlueCross BlueShield of Illinois',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'bluecross-blueshield-of-kansas',
        name: 'BlueCross BlueShield of Kansas',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'bluecross-blueshield-of-louisiana',
        name: 'BlueCross BlueShield of Louisiana',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'bluecross-blueshield-of-massachusetts',
        name: 'BlueCross BlueShield of Massachusetts',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'bluecross-blueshield-of-minnesota',
        name: 'BlueCross BlueShield of Minnesota',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'bluecross-blueshield-of-montana',
        name: 'BlueCross BlueShield of Montana',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'bluecross-blueshield-of-nebraska',
        name: 'BlueCross BlueShield of Nebraska',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'bluecross-blueshield-of-new-mexico',
        name: 'BlueCross BlueShield of New Mexico',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'bluecross-blueshield-of-north-carolina',
        name: 'BlueCross BlueShield of North Carolina',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'bluecross-blueshield-of-north-dakota',
        name: 'BlueCross BlueShield of North Dakota',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'bluecross-blueshield-of-oklahoma',
        name: 'BlueCross BlueShield of Oklahoma',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'bluecross-blueshield-of-rhode-island',
        name: 'BlueCross BlueShield of Rhode Island',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'bluecross-blueshield-of-tennessee',
        name: 'BlueCross BlueShield of Tennessee',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'bluecross-blueshield-of-texas',
        name: 'BlueCross BlueShield of Texas',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'bluecross-blueshield-of-vermont',
        name: 'BlueCross BlueShield of Vermont',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'bluecross-of-idaho',
        name: 'BlueCross of Idaho',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'blueshield-of-california',
        name: 'BlueShield of California',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'boon-chapman-cigna',
        name: 'Boon Chapman (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'boon-group-aetna',
        name: 'Boon Group (Aetna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'boon-chapman-aetna',
        name: 'Boon-Chapman (Aetna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'brms-cigna',
        name: 'BRMS (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'brms-partners-direct-health',
        name: 'BRMS (Partners Direct Health)',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'capital-blue-cross',
        name: 'Capital Blue Cross',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'carefirst-bluecross-blueshield-maryland-region',
        name: 'CareFirst BlueCross BlueShield - Maryland Region',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'carefirst-bluecross-blueshield-northern-virginia',
        name: 'CareFirst BlueCross BlueShield - Northern Virginia',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'carefirst-bluecross-blueshield-washington-dc-national-capital-area',
        name: 'CareFirst BlueCross BlueShield - Washington DC National Capital Area',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'carelon-behavioral-health',
        name: 'Carelon Behavioral Health',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'centene-national-delegation',
        name: 'Centene National Delegation',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'centivo',
        name: 'Centivo',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'centivo-cigna',
        name: 'Centivo (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'cigna',
        name: 'Cigna',
        aliases: [
          'Evernorth',
        ],
        featured: true,
        status: 'active',
        logo: '/images/carriers/cigna.png',
      },
      {
        id: 'claimdoc',
        name: 'ClaimDOC',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-90-degree-benefits',
        name: 'ClaimDOC - 90 Degree Benefits',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-acuity-group',
        name: 'ClaimDOC - Acuity Group',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-american-plan-administrators',
        name: 'ClaimDOC - American Plan Administrators',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-amwins-connect-administrators',
        name: 'ClaimDOC - AmWins Connect Administrators',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-assured-benefits-administrators',
        name: 'ClaimDOC - Assured Benefits Administrators',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-benefit-plan-administrators-aco',
        name: 'ClaimDOC - Benefit Plan Administrators ACO',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-benefit-plan-administrators-tpa',
        name: 'ClaimDOC - Benefit Plan Administrators TPA',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-benefit-risk-management-services',
        name: 'ClaimDOC - Benefit Risk Management Services',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-britton-benefit-services',
        name: 'ClaimDOC - Britton Benefit Services',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-carefactor',
        name: 'ClaimDOC - CareFactor',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-coastal-administrative-services',
        name: 'ClaimDOC - Coastal Administrative Services',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-diversified-group',
        name: 'ClaimDOC - Diversified Group',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-edison-health-solutions',
        name: 'ClaimDOC - Edison Health Solutions',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-group-administrators',
        name: 'ClaimDOC - Group Administrators',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-healthscope-benefits',
        name: 'ClaimDOC - HealthScope Benefits',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-jp-farley',
        name: 'ClaimDOC - JP Farley',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-lucent-health',
        name: 'ClaimDOC - Lucent Health',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-luminare-health',
        name: 'ClaimDOC - Luminare Health',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-marpai',
        name: 'ClaimDOC - Marpai',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-nova-healthcare-administrators',
        name: 'ClaimDOC - Nova Healthcare Administrators',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-preferred-benefit-administrators',
        name: 'ClaimDOC - Preferred Benefit Administrators',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-professional-benefit-administrators',
        name: 'ClaimDOC - Professional Benefit Administrators',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-qvi-risk-solutions',
        name: 'ClaimDOC - QVI Risk Solutions',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-sage',
        name: 'ClaimDOC - Sage',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-sisco-benefits',
        name: 'ClaimDOC - Sisco Benefits',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'claimdoc-the-loomis-company',
        name: 'ClaimDOC - The Loomis Company',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'coeur-cigna-network',
        name: 'Coeur (Cigna Network)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'collective-health-cigna',
        name: 'Collective Health (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'compass-rose-health-plans',
        name: 'Compass Rose Health Plans',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'consociate-health',
        name: 'Consociate Health',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'core-management-resources-partners-direct-health',
        name: 'Core Management Resources (Partners Direct Health)',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'curative-health-plan',
        name: 'Curative Health Plan',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'dean-health-plan-by-medica',
        name: 'Dean Health Plan by Medica',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'delta-health-systems-cigna',
        name: 'Delta Health Systems (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'detego-health-first-health-network',
        name: 'Detego Health (First Health Network)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'devoted-health-medicare-advantage',
        name: 'Devoted Health Medicare Advantage',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'diversified-administration-corporation-partners-direct-health',
        name: 'Diversified Administration Corporation (Partners Direct Health)',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'ebms-aetna',
        name: 'EBMS (Aetna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ebms-cigna',
        name: 'EBMS (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'ebms-partners-direct-health',
        name: 'EBMS (Partners Direct Health)',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'edison-health-solutions-partners-direct-health',
        name: 'Edison Health Solutions (Partners Direct Health)',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'eighth-district-ibew-electricians-cigna',
        name: 'Eighth District IBEW (Electricians) (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'emblem-health-unitedhealthcare',
        name: 'Emblem Health (UnitedHealthcare)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'emi-health-aetna',
        name: 'EMI Health (Aetna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'empire-bluecross-blueshield',
        name: 'Empire BlueCross BlueShield',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'evernorth',
        name: 'Evernorth',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'evolution-healthcare-evhc-aetna',
        name: 'Evolution Healthcare - EVHC (Aetna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'evolution-healthcare-evhc-cigna',
        name: 'Evolution Healthcare - EVHC (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'evolution-healthcare-evhc-partners-direct-health',
        name: 'Evolution Healthcare - EVHC (Partners Direct Health)',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'excellus-bluecross-blueshield',
        name: 'Excellus BlueCross BlueShield',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'firefly-health',
        name: 'Firefly Health',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'first-choice-health',
        name: 'First Choice Health',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'florida-blue',
        name: 'Florida Blue',
        aliases: [
          'BCBS Florida',
          'Blue Cross Blue Shield of Florida',
        ],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'florida-blue-medicare-advantage',
        name: 'Florida Blue Medicare Advantage',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'fringe-benefit-group-first-health-network',
        name: 'Fringe Benefit Group (First Health Network)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'geha-unitedhealthcare',
        name: 'GEHA - UnitedHealthcare',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'geisinger-health-plan-cigna',
        name: 'Geisinger Health Plan (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'gravie-administrative-services-aetna',
        name: 'Gravie Administrative Services (Aetna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'gravie-administrative-services-cigna',
        name: 'Gravie Administrative Services (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'hawaii-medical-service-association-bluecross-blueshield-of-hawaii',
        name: 'Hawaii Medical Service Association | BlueCross BlueShield of Hawaii',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'health-net-cigna',
        name: 'Health Net (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'health-plans-inc-cigna',
        name: 'Health Plans, Inc. (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'health-plans-inc-first-health-network',
        name: 'Health Plans, Inc. (First Health Network)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'healthez-aetna',
        name: 'HealthEZ (Aetna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'healthez-cigna',
        name: 'HealthEZ (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'healthgram-cigna',
        name: 'Healthgram (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'healthscope-benefits-unitedhealthcare',
        name: 'HealthScope Benefits - UnitedHealthcare',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'healthscope-benefits-partners-direct-health',
        name: 'HealthSCOPE Benefits (Partners Direct Health)',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'healthsmart-partners-direct-health',
        name: 'HealthSmart (Partners Direct Health)',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'healthsmart-unitedhealthcare',
        name: 'HealthSmart (UnitedHealthcare)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'healthsmart-benefits-cigna',
        name: 'HealthSmart Benefits (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'highmark-blue-cross-blueshield-of-delaware',
        name: 'Highmark Blue Cross BlueShield of Delaware',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'highmark-blue-cross-blueshield-of-west-virginia',
        name: 'Highmark Blue Cross BlueShield of West Virginia',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'highmark-blue-cross-blueshield-of-western-pennsylvania',
        name: 'Highmark Blue Cross BlueShield of Western Pennsylvania',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'highmark-bluecross-blueshield-of-northeastern-pennsylvania',
        name: 'Highmark BlueCross BlueShield of Northeastern Pennsylvania',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'highmark-bluecross-blueshield-of-western-new-york',
        name: 'Highmark BlueCross BlueShield of Western New York',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'hooray-health-first-health-network',
        name: 'Hooray Health (First Health Network)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'horizon-blue-cross-blue-shield-of-new-jersey',
        name: 'Horizon Blue Cross Blue Shield of New Jersey',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'humana-medicare-advantage',
        name: 'Humana Medicare Advantage',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'iba-partners-direct-health',
        name: 'IBA (Partners Direct Health)',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'imagine-health',
        name: 'Imagine Health',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'imagine360',
        name: 'Imagine360',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'independence-blue-cross-pennsylvania-virtual-network',
        name: 'Independence Blue Cross Pennsylvania (Virtual Network)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'independence-bluecross',
        name: 'Independence BlueCross',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'insurance-program-managers-group-partners-direct-health',
        name: 'Insurance Program Managers Group (Partners Direct Health)',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'insurance-services-of-lubbock-partners-direct-health',
        name: 'Insurance Services of Lubbock (Partners Direct Health)',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'johns-hopkins-health-plans-cigna',
        name: 'Johns Hopkins Health Plans (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'judi-health-cigna',
        name: 'Judi Health (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'keenan-claimdoc',
        name: 'Keenan (ClaimDOC)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'lucent-health-aetna',
        name: 'Lucent Health (Aetna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'lucent-health-cigna',
        name: 'Lucent Health (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'luminare-health-35182-aetna',
        name: 'Luminare Health (35182 - Aetna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'luminare-health-38225-aetna',
        name: 'Luminare Health (38225 - Aetna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'luminare-health-cigna',
        name: 'Luminare Health (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'luminare-health-partners-direct-health',
        name: 'Luminare Health (Partners Direct Health)',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'magnacare-first-health-network',
        name: 'Magnacare (First Health Network)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'marpai-health-aetna',
        name: 'Marpai Health (Aetna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'marpai-health-cigna',
        name: 'Marpai Health (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'medben-partners-direct-health',
        name: 'MedBen (Partners Direct Health)',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'medica-aetna',
        name: 'Medica (Aetna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'medica-first-health-network',
        name: 'Medica (First Health Network)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'medical-mutual-cigna',
        name: 'Medical Mutual (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'merchants-benefit-administration-inc',
        name: 'Merchants Benefit Administration, Inc.',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'meritain-health',
        name: 'Meritain Health',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'motivhealth-cigna',
        name: 'MotivHealth (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'nalc-health-benefit-plan-cigna',
        name: 'NALC Health Benefit Plan (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'nesika-health-cigna',
        name: 'Nesika Health (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'nippon-life-benefits-aetna',
        name: 'Nippon Life Benefits (Aetna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'oscar',
        name: 'Oscar (Optum)',
        aliases: [
          'Oscar',
          'Oscar Health',
        ],
        featured: true,
        status: 'active',
        logo: '/images/carriers/oscar.svg',
      },
      {
        id: 'oxford-optum',
        name: 'Oxford (Optum)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'partners-direct-health',
        name: 'Partners Direct Health',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'peak-health-aetna',
        name: 'Peak Health (Aetna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'personify-health-aetna',
        name: 'Personify Health (Aetna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'personify-health-cigna',
        name: 'Personify Health (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'personify-health-partners-direct-health',
        name: 'Personify Health (Partners Direct Health)',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'point-c-insurance-administrators-of-america-cigna',
        name: 'Point C (Insurance Administrators of America - Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'premera-blue-cross-of-washington',
        name: 'Premera Blue Cross of Washington',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'premera-bluecross-blueshield-of-alaska',
        name: 'Premera BlueCross BlueShield of Alaska',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'priority-health-cigna',
        name: 'Priority Health (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'professional-benefit-administrators-inc-cigna',
        name: 'Professional Benefit Administrators, Inc. (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'providence-health-plan-cigna',
        name: 'Providence Health Plan (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'reflect-health-cigna',
        name: 'Reflect Health (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'regence-blue-cross-blueshield-of-utah',
        name: 'Regence Blue Cross BlueShield of Utah',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'regence-bluecross-blueshield-of-oregon',
        name: 'Regence BlueCross BlueShield of Oregon',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'regence-blueshield-of-idaho',
        name: 'Regence BlueShield of Idaho',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'regence-blueshield-of-washington-counties',
        name: 'Regence BlueShield of Washington Counties',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'regence-group-administrators',
        name: 'Regence Group Administrators',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'ridge-administrative-services-cigna',
        name: 'Ridge Administrative Services (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 's-and-s-health-aetna',
        name: 'S & S Health (Aetna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 's-and-s-health-cigna',
        name: 'S & S Health (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'sage-tpa-cigna',
        name: 'Sage TPA (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'samera-health-first-health-network',
        name: 'Samera Health (First Health Network)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'sana-benefits',
        name: 'Sana Benefits',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'sidecar-health',
        name: 'Sidecar Health',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'simplan-cigna',
        name: 'Simplan (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'simplified-benefits-administrators',
        name: 'Simplified Benefits Administrators',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'sisco-cigna',
        name: 'SisCo (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'sisco-partners-direct-health',
        name: 'SisCo (Partners Direct Health)',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'surest',
        name: 'Surest',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'sutterselect-unitedhealthcare',
        name: 'SutterSelect (UnitedHealthcare)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'teamsters-local-115-cigna',
        name: 'Teamsters Local 115 (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'teamsters-local-206-cigna',
        name: 'Teamsters Local 206 (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'the-alliance-uhc-network',
        name: 'The Alliance - UHC Network',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'the-health-plan-cigna',
        name: 'The Health Plan (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'the-health-plan-first-health-network',
        name: 'The Health Plan (First Health Network)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'the-health-plan-partners-direct-health',
        name: 'The Health Plan (Partners Direct Health)',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'the-loomis-company-cigna-network',
        name: 'The Loomis Company - Cigna Network',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'tlc-benefits-solutions-partners-direct-health',
        name: 'TLC Benefits Solutions (Partners Direct Health)',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'total-plan-concepts-partners-direct-health',
        name: 'Total Plan Concepts (Partners Direct Health)',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'trustmark-aetna',
        name: 'Trustmark (Aetna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'umr',
        name: 'UMR',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'unified-group-services-cigna',
        name: 'Unified Group Services (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'unite-us-cigna',
        name: 'Unite Us (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'unitedhealthcare',
        name: 'UnitedHealthcare (Optum)',
        aliases: [
          'UHC',
          'United',
          'United Healthcare',
          'Optum',
          'UnitedHealthcare',
        ],
        featured: true,
        status: 'active',
        logo: '/images/carriers/unitedhealthcare.svg',
      },
      {
        id: 'unitedhealthcare-global',
        name: 'UnitedHealthcare Global',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'unitedhealthcare-medicare-advantage',
        name: 'UnitedHealthcare Medicare Advantage',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'unitedhealthcare-shared-services',
        name: 'UnitedHealthcare Shared Services',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'unitedhealthcare-student-resources',
        name: 'UnitedHealthcare Student Resources',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'unitedhealthcare-golden-rule-insurance-co',
        name: 'UnitedHealthcare/Golden Rule Insurance Co.',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'upmc-health-plan-cigna',
        name: 'UPMC Health Plan (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'uprise-health-hmc-healthworks-cigna',
        name: 'Uprise Health HMC Healthworks (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'varipro-partners-direct-health',
        name: 'Varipro (Partners Direct Health)',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'webtpa-aetna',
        name: 'WebTPA (Aetna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'webtpa-cigna',
        name: 'WebTPA (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'wellmark-bluecross-blueshield-of-iowa',
        name: 'Wellmark BlueCross BlueShield of Iowa',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'wellmark-bluecross-blueshield-of-south-dakota',
        name: 'Wellmark BlueCross BlueShield of South Dakota',
        aliases: [],
        featured: false,
        status: 'coming-soon',
        logo: '',
      },
      {
        id: 'yuzu-health-cigna',
        name: 'Yuzu Health (Cigna)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
      {
        id: 'yuzu-health-first-health',
        name: 'Yuzu Health (First Health)',
        aliases: [],
        featured: false,
        status: 'active',
        logo: '',
      },
    ] as Array<{
      id: string;
      name: string;
      aliases: string[];
      featured: boolean;
      status: 'active' | 'coming-soon';
      logo: string;
    }>,
  },

  services: [
    'Individual therapy',
    'Couples therapy',
    'Family therapy',
    'Group therapy',
    'Psychological assessments',
    'Consultation',
  ],

  specialties: [
    'Anxiety',
    'Depression',
    'Trauma & PTSD',
    'EMDR',
    'LGBTQ+ Affirming Care',
    'Gender Identity',
    'Women’s Mental Health',
    'Relationship Challenges',
    'Stress & Burnout',
    'Life Transitions',
    'Self-Esteem',
    'Grief & Loss',
    'Young Adults',
    'Communication & Boundaries',
  ],
} as const;

/** Formspree endpoint for contact form */
export function getFormspreeUrl(): string {
  return `https://formspree.io/f/${siteConfig.formspreeFormId}`;
}

export const navLinks = [
  { href: '/', label: 'Home' },
  { href: '/about', label: 'Why Woven Sage' },
  { href: '/services', label: 'Services' },
  { href: '/team', label: 'Team' },
  { href: '/insurance', label: 'Insurance' },
  { href: '/faq', label: 'FAQ' },
] as const;

export const footerLinks = [
  { href: '/resources', label: 'Resources' },
  { href: '/blog', label: 'Blog' },
  { href: '/careers', label: 'Careers' },
  { href: '/wsp', label: 'WSP App' },
  { href: '/privacy', label: 'Privacy Policy' },
] as const;

export const socialLinks = [
  { key: 'linkedin', label: 'LinkedIn' },
  { key: 'instagram', label: 'Instagram' },
  { key: 'tiktok', label: 'TikTok' },
  { key: 'facebook', label: 'Facebook' },
] as const;
